version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notebook-app
    container_name: notebook-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: notebook-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
